/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package source;
import java.util.Scanner;
import java.io.*;

public class App {
    public String getGreeting() {
        return "";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());
        Battleship game = new Battleship();
        try {
            game.play();
        }
        catch (IOException e){
            System.out.println(e);
        }

        //Scanner sc = new Scanner(System.in);
        //while(sc.hasNext()) {
        //    System.out.println("echo:"+sc.nextLine());
        //}
    }
}
