/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package source;
import javax.swing.*;
import java.util.Scanner;
import java.io.*;

// test entry: a new branch
public class App {
    public String getGreeting() {
        return "";
    }

    public static void main(String[] args) throws ClassNotFoundException, UnsupportedLookAndFeelException, IllegalAccessException, InstantiationException {

        System.out.println(new App().getGreeting());
        BattleshipGame game = new BattleshipGame();


        try {
            game.play();
        }
        catch (IOException e){
            System.out.println(e);
        }

        input.reader.close();
    }
}
